// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNotify.proto

package com.liteiot.admin.modules.admin.protobuf;

public final class ClientNotify {
  private ClientNotify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface clientNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liteiot.common.vo.protobuf.clientNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool alarmNotify = 1;</code>
     */
    boolean getAlarmNotify();

    /**
     * <code>bool groupChange = 2;</code>
     */
    boolean getGroupChange();

    /**
     * <code>bool statusChange = 3;</code>
     */
    boolean getStatusChange();

    /**
     * <code>string imei = 4;</code>
     */
    String getImei();
    /**
     * <code>string imei = 4;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <code>int64 msgCount = 5;</code>
     */
    long getMsgCount();
  }
  /**
   * Protobuf type {@code com.liteiot.common.vo.protobuf.clientNotify}
   */
  public  static final class clientNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liteiot.common.vo.protobuf.clientNotify)
      clientNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use clientNotify.newBuilder() to construct.
    private clientNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private clientNotify() {
      imei_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private clientNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              alarmNotify_ = input.readBool();
              break;
            }
            case 16: {

              groupChange_ = input.readBool();
              break;
            }
            case 24: {

              statusChange_ = input.readBool();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              imei_ = s;
              break;
            }
            case 40: {

              msgCount_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clientNotify.class, Builder.class);
    }

    public static final int ALARMNOTIFY_FIELD_NUMBER = 1;
    private boolean alarmNotify_;
    /**
     * <code>bool alarmNotify = 1;</code>
     */
    public boolean getAlarmNotify() {
      return alarmNotify_;
    }

    public static final int GROUPCHANGE_FIELD_NUMBER = 2;
    private boolean groupChange_;
    /**
     * <code>bool groupChange = 2;</code>
     */
    public boolean getGroupChange() {
      return groupChange_;
    }

    public static final int STATUSCHANGE_FIELD_NUMBER = 3;
    private boolean statusChange_;
    /**
     * <code>bool statusChange = 3;</code>
     */
    public boolean getStatusChange() {
      return statusChange_;
    }

    public static final int IMEI_FIELD_NUMBER = 4;
    private volatile Object imei_;
    /**
     * <code>string imei = 4;</code>
     */
    public String getImei() {
      Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      }
    }
    /**
     * <code>string imei = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCOUNT_FIELD_NUMBER = 5;
    private long msgCount_;
    /**
     * <code>int64 msgCount = 5;</code>
     */
    public long getMsgCount() {
      return msgCount_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (alarmNotify_ != false) {
        output.writeBool(1, alarmNotify_);
      }
      if (groupChange_ != false) {
        output.writeBool(2, groupChange_);
      }
      if (statusChange_ != false) {
        output.writeBool(3, statusChange_);
      }
      if (!getImeiBytes().isEmpty()) {
        writeString(output, 4, imei_);
      }
      if (msgCount_ != 0L) {
        output.writeInt64(5, msgCount_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (alarmNotify_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, alarmNotify_);
      }
      if (groupChange_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, groupChange_);
      }
      if (statusChange_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, statusChange_);
      }
      if (!getImeiBytes().isEmpty()) {
        size += computeStringSize(4, imei_);
      }
      if (msgCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, msgCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clientNotify)) {
        return super.equals(obj);
      }
      clientNotify other = (clientNotify) obj;

      if (getAlarmNotify()
          != other.getAlarmNotify()) return false;
      if (getGroupChange()
          != other.getGroupChange()) return false;
      if (getStatusChange()
          != other.getStatusChange()) return false;
      if (!getImei()
          .equals(other.getImei())) return false;
      if (getMsgCount()
          != other.getMsgCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALARMNOTIFY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAlarmNotify());
      hash = (37 * hash) + GROUPCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGroupChange());
      hash = (37 * hash) + STATUSCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatusChange());
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getImei().hashCode();
      hash = (37 * hash) + MSGCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clientNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clientNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clientNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clientNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clientNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clientNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clientNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input);
    }
    public static clientNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clientNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedWithIOException(PARSER, input);
    }
    public static clientNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clientNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input);
    }
    public static clientNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clientNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liteiot.common.vo.protobuf.clientNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liteiot.common.vo.protobuf.clientNotify)
        clientNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clientNotify.class, Builder.class);
      }

      // Construct using com.liteiot.common.vo.protobuf.ClientNotify.clientNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        alarmNotify_ = false;

        groupChange_ = false;

        statusChange_ = false;

        imei_ = "";

        msgCount_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor;
      }

      @Override
      public clientNotify getDefaultInstanceForType() {
        return clientNotify.getDefaultInstance();
      }

      @Override
      public clientNotify build() {
        clientNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public clientNotify buildPartial() {
        clientNotify result = new clientNotify(this);
        result.alarmNotify_ = alarmNotify_;
        result.groupChange_ = groupChange_;
        result.statusChange_ = statusChange_;
        result.imei_ = imei_;
        result.msgCount_ = msgCount_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clientNotify) {
          return mergeFrom((clientNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clientNotify other) {
        if (other == clientNotify.getDefaultInstance()) return this;
        if (other.getAlarmNotify() != false) {
          setAlarmNotify(other.getAlarmNotify());
        }
        if (other.getGroupChange() != false) {
          setGroupChange(other.getGroupChange());
        }
        if (other.getStatusChange() != false) {
          setStatusChange(other.getStatusChange());
        }
        if (!other.getImei().isEmpty()) {
          imei_ = other.imei_;
          onChanged();
        }
        if (other.getMsgCount() != 0L) {
          setMsgCount(other.getMsgCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clientNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clientNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean alarmNotify_ ;
      /**
       * <code>bool alarmNotify = 1;</code>
       */
      public boolean getAlarmNotify() {
        return alarmNotify_;
      }
      /**
       * <code>bool alarmNotify = 1;</code>
       */
      public Builder setAlarmNotify(boolean value) {
        
        alarmNotify_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool alarmNotify = 1;</code>
       */
      public Builder clearAlarmNotify() {
        
        alarmNotify_ = false;
        onChanged();
        return this;
      }

      private boolean groupChange_ ;
      /**
       * <code>bool groupChange = 2;</code>
       */
      public boolean getGroupChange() {
        return groupChange_;
      }
      /**
       * <code>bool groupChange = 2;</code>
       */
      public Builder setGroupChange(boolean value) {
        
        groupChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool groupChange = 2;</code>
       */
      public Builder clearGroupChange() {
        
        groupChange_ = false;
        onChanged();
        return this;
      }

      private boolean statusChange_ ;
      /**
       * <code>bool statusChange = 3;</code>
       */
      public boolean getStatusChange() {
        return statusChange_;
      }
      /**
       * <code>bool statusChange = 3;</code>
       */
      public Builder setStatusChange(boolean value) {
        
        statusChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool statusChange = 3;</code>
       */
      public Builder clearStatusChange() {
        
        statusChange_ = false;
        onChanged();
        return this;
      }

      private Object imei_ = "";
      /**
       * <code>string imei = 4;</code>
       */
      public String getImei() {
        Object ref = imei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string imei = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imei = 4;</code>
       */
      public Builder setImei(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 4;</code>
       */
      public Builder clearImei() {
        
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 4;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imei_ = value;
        onChanged();
        return this;
      }

      private long msgCount_ ;
      /**
       * <code>int64 msgCount = 5;</code>
       */
      public long getMsgCount() {
        return msgCount_;
      }
      /**
       * <code>int64 msgCount = 5;</code>
       */
      public Builder setMsgCount(long value) {
        
        msgCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgCount = 5;</code>
       */
      public Builder clearMsgCount() {
        
        msgCount_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liteiot.common.vo.protobuf.clientNotify)
    }

    // @@protoc_insertion_point(class_scope:com.liteiot.common.vo.protobuf.clientNotify)
    private static final clientNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clientNotify();
    }

    public static clientNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<clientNotify>
        PARSER = new com.google.protobuf.AbstractParser<clientNotify>() {
      @Override
      public clientNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new clientNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<clientNotify> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<clientNotify> getParserForType() {
      return PARSER;
    }

    @Override
    public clientNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface userCheckinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liteiot.common.vo.protobuf.userCheckin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string bearer = 1;</code>
     */
    String getBearer();
    /**
     * <code>string bearer = 1;</code>
     */
    com.google.protobuf.ByteString
        getBearerBytes();
  }
  /**
   * Protobuf type {@code com.liteiot.common.vo.protobuf.userCheckin}
   */
  public  static final class userCheckin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liteiot.common.vo.protobuf.userCheckin)
      userCheckinOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use userCheckin.newBuilder() to construct.
    private userCheckin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private userCheckin() {
      bearer_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private userCheckin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              bearer_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              userCheckin.class, Builder.class);
    }

    public static final int BEARER_FIELD_NUMBER = 1;
    private volatile Object bearer_;
    /**
     * <code>string bearer = 1;</code>
     */
    public String getBearer() {
      Object ref = bearer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bearer_ = s;
        return s;
      }
    }
    /**
     * <code>string bearer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBearerBytes() {
      Object ref = bearer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bearer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBearerBytes().isEmpty()) {
        writeString(output, 1, bearer_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBearerBytes().isEmpty()) {
        size += computeStringSize(1, bearer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof userCheckin)) {
        return super.equals(obj);
      }
      userCheckin other = (userCheckin) obj;

      if (!getBearer()
          .equals(other.getBearer())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BEARER_FIELD_NUMBER;
      hash = (53 * hash) + getBearer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static userCheckin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userCheckin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userCheckin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userCheckin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userCheckin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userCheckin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userCheckin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input);
    }
    public static userCheckin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static userCheckin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedWithIOException(PARSER, input);
    }
    public static userCheckin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static userCheckin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input);
    }
    public static userCheckin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(userCheckin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liteiot.common.vo.protobuf.userCheckin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liteiot.common.vo.protobuf.userCheckin)
        userCheckinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                userCheckin.class, Builder.class);
      }

      // Construct using com.liteiot.common.vo.protobuf.ClientNotify.userCheckin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bearer_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientNotify.internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor;
      }

      @Override
      public userCheckin getDefaultInstanceForType() {
        return userCheckin.getDefaultInstance();
      }

      @Override
      public userCheckin build() {
        userCheckin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public userCheckin buildPartial() {
        userCheckin result = new userCheckin(this);
        result.bearer_ = bearer_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof userCheckin) {
          return mergeFrom((userCheckin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(userCheckin other) {
        if (other == userCheckin.getDefaultInstance()) return this;
        if (!other.getBearer().isEmpty()) {
          bearer_ = other.bearer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        userCheckin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (userCheckin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object bearer_ = "";
      /**
       * <code>string bearer = 1;</code>
       */
      public String getBearer() {
        Object ref = bearer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bearer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string bearer = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBearerBytes() {
        Object ref = bearer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bearer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bearer = 1;</code>
       */
      public Builder setBearer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bearer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bearer = 1;</code>
       */
      public Builder clearBearer() {
        
        bearer_ = getDefaultInstance().getBearer();
        onChanged();
        return this;
      }
      /**
       * <code>string bearer = 1;</code>
       */
      public Builder setBearerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bearer_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liteiot.common.vo.protobuf.userCheckin)
    }

    // @@protoc_insertion_point(class_scope:com.liteiot.common.vo.protobuf.userCheckin)
    private static final userCheckin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new userCheckin();
    }

    public static userCheckin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<userCheckin>
        PARSER = new com.google.protobuf.AbstractParser<userCheckin>() {
      @Override
      public userCheckin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new userCheckin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<userCheckin> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<userCheckin> getParserForType() {
      return PARSER;
    }

    @Override
    public userCheckin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ClientNotify.proto\022*com.liteiot.admin.m" +
      "odules.admin.vo.protobuf\"n\n\014clientNotify" +
      "\022\023\n\013alarmNotify\030\001 \001(\010\022\023\n\013groupChange\030\002 \001" +
      "(\010\022\024\n\014statusChange\030\003 \001(\010\022\014\n\004imei\030\004 \001(\t\022\020" +
      "\n\010msgCount\030\005 \001(\003\"\035\n\013userCheckin\022\016\n\006beare" +
      "r\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_beidou_admin_modules_admin_vo_protobuf_clientNotify_descriptor,
        new String[] { "AlarmNotify", "GroupChange", "StatusChange", "Imei", "MsgCount", });
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_beidou_admin_modules_admin_vo_protobuf_userCheckin_descriptor,
        new String[] { "Bearer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
