// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: li-admin/src/main/resources/Protobuf/RealTimePacket.proto

package com.liteiot.admin.modules.admin.protobuf;

public final class RealTimePacket {
  private RealTimePacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RealTimePacketInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string imei = 1;</code>
     */
    java.lang.String getImei();
    /**
     * <code>string imei = 1;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <code>int32 batteryLevel = 2;</code>
     */
    int getBatteryLevel();

    /**
     * <code>double leanDegrees = 3;</code>
     */
    double getLeanDegrees();

    /**
     * <code>int64 reportTime = 4;</code>
     */
    long getReportTime();

    /**
     * <pre>
     * 方向(单位为度数)
     * </pre>
     *
     * <code>double degree = 5;</code>
     */
    double getDegree();

    /**
     * <pre>
     * 唯一
     * </pre>
     *
     * <code>double displacement = 6;</code>
     */
    double getDisplacement();

    /**
     * <pre>
     * 方位角
     * </pre>
     *
     * <code>string azimuth = 7;</code>
     */
    java.lang.String getAzimuth();
    /**
     * <pre>
     * 方位角
     * </pre>
     *
     * <code>string azimuth = 7;</code>
     */
    com.google.protobuf.ByteString
        getAzimuthBytes();
  }
  /**
   * Protobuf type {@code com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo}
   */
  public  static final class RealTimePacketInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo)
      RealTimePacketInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RealTimePacketInfo.newBuilder() to construct.
    private RealTimePacketInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RealTimePacketInfo() {
      imei_ = "";
      azimuth_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RealTimePacketInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              imei_ = s;
              break;
            }
            case 16: {

              batteryLevel_ = input.readInt32();
              break;
            }
            case 25: {

              leanDegrees_ = input.readDouble();
              break;
            }
            case 32: {

              reportTime_ = input.readInt64();
              break;
            }
            case 41: {

              degree_ = input.readDouble();
              break;
            }
            case 49: {

              displacement_ = input.readDouble();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              azimuth_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.class, com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.Builder.class);
    }

    public static final int IMEI_FIELD_NUMBER = 1;
    private volatile java.lang.Object imei_;
    /**
     * <code>string imei = 1;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      }
    }
    /**
     * <code>string imei = 1;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATTERYLEVEL_FIELD_NUMBER = 2;
    private int batteryLevel_;
    /**
     * <code>int32 batteryLevel = 2;</code>
     */
    public int getBatteryLevel() {
      return batteryLevel_;
    }

    public static final int LEANDEGREES_FIELD_NUMBER = 3;
    private double leanDegrees_;
    /**
     * <code>double leanDegrees = 3;</code>
     */
    public double getLeanDegrees() {
      return leanDegrees_;
    }

    public static final int REPORTTIME_FIELD_NUMBER = 4;
    private long reportTime_;
    /**
     * <code>int64 reportTime = 4;</code>
     */
    public long getReportTime() {
      return reportTime_;
    }

    public static final int DEGREE_FIELD_NUMBER = 5;
    private double degree_;
    /**
     * <pre>
     * 方向(单位为度数)
     * </pre>
     *
     * <code>double degree = 5;</code>
     */
    public double getDegree() {
      return degree_;
    }

    public static final int DISPLACEMENT_FIELD_NUMBER = 6;
    private double displacement_;
    /**
     * <pre>
     * 唯一
     * </pre>
     *
     * <code>double displacement = 6;</code>
     */
    public double getDisplacement() {
      return displacement_;
    }

    public static final int AZIMUTH_FIELD_NUMBER = 7;
    private volatile java.lang.Object azimuth_;
    /**
     * <pre>
     * 方位角
     * </pre>
     *
     * <code>string azimuth = 7;</code>
     */
    public java.lang.String getAzimuth() {
      java.lang.Object ref = azimuth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        azimuth_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 方位角
     * </pre>
     *
     * <code>string azimuth = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAzimuthBytes() {
      java.lang.Object ref = azimuth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        azimuth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, imei_);
      }
      if (batteryLevel_ != 0) {
        output.writeInt32(2, batteryLevel_);
      }
      if (leanDegrees_ != 0D) {
        output.writeDouble(3, leanDegrees_);
      }
      if (reportTime_ != 0L) {
        output.writeInt64(4, reportTime_);
      }
      if (degree_ != 0D) {
        output.writeDouble(5, degree_);
      }
      if (displacement_ != 0D) {
        output.writeDouble(6, displacement_);
      }
      if (!getAzimuthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, azimuth_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, imei_);
      }
      if (batteryLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, batteryLevel_);
      }
      if (leanDegrees_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, leanDegrees_);
      }
      if (reportTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, reportTime_);
      }
      if (degree_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, degree_);
      }
      if (displacement_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, displacement_);
      }
      if (!getAzimuthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, azimuth_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo)) {
        return super.equals(obj);
      }
      com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo other = (com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo) obj;

      if (!getImei()
          .equals(other.getImei())) return false;
      if (getBatteryLevel()
          != other.getBatteryLevel()) return false;
      if (java.lang.Double.doubleToLongBits(getLeanDegrees())
          != java.lang.Double.doubleToLongBits(
              other.getLeanDegrees())) return false;
      if (getReportTime()
          != other.getReportTime()) return false;
      if (java.lang.Double.doubleToLongBits(getDegree())
          != java.lang.Double.doubleToLongBits(
              other.getDegree())) return false;
      if (java.lang.Double.doubleToLongBits(getDisplacement())
          != java.lang.Double.doubleToLongBits(
              other.getDisplacement())) return false;
      if (!getAzimuth()
          .equals(other.getAzimuth())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getImei().hashCode();
      hash = (37 * hash) + BATTERYLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryLevel();
      hash = (37 * hash) + LEANDEGREES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLeanDegrees()));
      hash = (37 * hash) + REPORTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReportTime());
      hash = (37 * hash) + DEGREE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDegree()));
      hash = (37 * hash) + DISPLACEMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDisplacement()));
      hash = (37 * hash) + AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + getAzimuth().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo)
        com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.class, com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.Builder.class);
      }

      // Construct using com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        imei_ = "";

        batteryLevel_ = 0;

        leanDegrees_ = 0D;

        reportTime_ = 0L;

        degree_ = 0D;

        displacement_ = 0D;

        azimuth_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor;
      }

      @java.lang.Override
      public com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo getDefaultInstanceForType() {
        return com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo build() {
        com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo buildPartial() {
        com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo result = new com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo(this);
        result.imei_ = imei_;
        result.batteryLevel_ = batteryLevel_;
        result.leanDegrees_ = leanDegrees_;
        result.reportTime_ = reportTime_;
        result.degree_ = degree_;
        result.displacement_ = displacement_;
        result.azimuth_ = azimuth_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo) {
          return mergeFrom((com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo other) {
        if (other == com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo.getDefaultInstance()) return this;
        if (!other.getImei().isEmpty()) {
          imei_ = other.imei_;
          onChanged();
        }
        if (other.getBatteryLevel() != 0) {
          setBatteryLevel(other.getBatteryLevel());
        }
        if (other.getLeanDegrees() != 0D) {
          setLeanDegrees(other.getLeanDegrees());
        }
        if (other.getReportTime() != 0L) {
          setReportTime(other.getReportTime());
        }
        if (other.getDegree() != 0D) {
          setDegree(other.getDegree());
        }
        if (other.getDisplacement() != 0D) {
          setDisplacement(other.getDisplacement());
        }
        if (!other.getAzimuth().isEmpty()) {
          azimuth_ = other.azimuth_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object imei_ = "";
      /**
       * <code>string imei = 1;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imei = 1;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imei = 1;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 1;</code>
       */
      public Builder clearImei() {
        
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>string imei = 1;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imei_ = value;
        onChanged();
        return this;
      }

      private int batteryLevel_ ;
      /**
       * <code>int32 batteryLevel = 2;</code>
       */
      public int getBatteryLevel() {
        return batteryLevel_;
      }
      /**
       * <code>int32 batteryLevel = 2;</code>
       */
      public Builder setBatteryLevel(int value) {
        
        batteryLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batteryLevel = 2;</code>
       */
      public Builder clearBatteryLevel() {
        
        batteryLevel_ = 0;
        onChanged();
        return this;
      }

      private double leanDegrees_ ;
      /**
       * <code>double leanDegrees = 3;</code>
       */
      public double getLeanDegrees() {
        return leanDegrees_;
      }
      /**
       * <code>double leanDegrees = 3;</code>
       */
      public Builder setLeanDegrees(double value) {
        
        leanDegrees_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double leanDegrees = 3;</code>
       */
      public Builder clearLeanDegrees() {
        
        leanDegrees_ = 0D;
        onChanged();
        return this;
      }

      private long reportTime_ ;
      /**
       * <code>int64 reportTime = 4;</code>
       */
      public long getReportTime() {
        return reportTime_;
      }
      /**
       * <code>int64 reportTime = 4;</code>
       */
      public Builder setReportTime(long value) {
        
        reportTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 reportTime = 4;</code>
       */
      public Builder clearReportTime() {
        
        reportTime_ = 0L;
        onChanged();
        return this;
      }

      private double degree_ ;
      /**
       * <pre>
       * 方向(单位为度数)
       * </pre>
       *
       * <code>double degree = 5;</code>
       */
      public double getDegree() {
        return degree_;
      }
      /**
       * <pre>
       * 方向(单位为度数)
       * </pre>
       *
       * <code>double degree = 5;</code>
       */
      public Builder setDegree(double value) {
        
        degree_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方向(单位为度数)
       * </pre>
       *
       * <code>double degree = 5;</code>
       */
      public Builder clearDegree() {
        
        degree_ = 0D;
        onChanged();
        return this;
      }

      private double displacement_ ;
      /**
       * <pre>
       * 唯一
       * </pre>
       *
       * <code>double displacement = 6;</code>
       */
      public double getDisplacement() {
        return displacement_;
      }
      /**
       * <pre>
       * 唯一
       * </pre>
       *
       * <code>double displacement = 6;</code>
       */
      public Builder setDisplacement(double value) {
        
        displacement_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 唯一
       * </pre>
       *
       * <code>double displacement = 6;</code>
       */
      public Builder clearDisplacement() {
        
        displacement_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object azimuth_ = "";
      /**
       * <pre>
       * 方位角
       * </pre>
       *
       * <code>string azimuth = 7;</code>
       */
      public java.lang.String getAzimuth() {
        java.lang.Object ref = azimuth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          azimuth_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 方位角
       * </pre>
       *
       * <code>string azimuth = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAzimuthBytes() {
        java.lang.Object ref = azimuth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          azimuth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 方位角
       * </pre>
       *
       * <code>string azimuth = 7;</code>
       */
      public Builder setAzimuth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        azimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方位角
       * </pre>
       *
       * <code>string azimuth = 7;</code>
       */
      public Builder clearAzimuth() {
        
        azimuth_ = getDefaultInstance().getAzimuth();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方位角
       * </pre>
       *
       * <code>string azimuth = 7;</code>
       */
      public Builder setAzimuthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        azimuth_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo)
    }

    // @@protoc_insertion_point(class_scope:com.liteiot.admin.modules.admin.protobuf.RealTimePacketInfo)
    private static final com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo();
    }

    public static com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RealTimePacketInfo>
        PARSER = new com.google.protobuf.AbstractParser<RealTimePacketInfo>() {
      @java.lang.Override
      public RealTimePacketInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RealTimePacketInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RealTimePacketInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RealTimePacketInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.liteiot.admin.modules.admin.protobuf.RealTimePacket.RealTimePacketInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:li-admin/src/main/resources/Protobuf/" +
      "RealTimePacket.proto\022\'com.liteiot.admin.m" +
      "odules.admin.protobuf\"\230\001\n\022RealTimePacket" +
      "Info\022\014\n\004imei\030\001 \001(\t\022\024\n\014batteryLevel\030\002 \001(\005" +
      "\022\023\n\013leanDegrees\030\003 \001(\001\022\022\n\nreportTime\030\004 \001(" +
      "\003\022\016\n\006degree\030\005 \001(\001\022\024\n\014displacement\030\006 \001(\001\022" +
      "\017\n\007azimuth\030\007 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_beidou_admin_modules_admin_protobuf_RealTimePacketInfo_descriptor,
        new java.lang.String[] { "Imei", "BatteryLevel", "LeanDegrees", "ReportTime", "Degree", "Displacement", "Azimuth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
